# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.1-snapshot-1
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

# Mod Properties
mod_version=3.0-snapshot
maven_group=com.kr1s1s.subtlyd
archives_base_name=subtlyd

# Dependencies
fabric_version=0.140.2+26.1