# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=26.3-snapshot-9
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=5.0-snapshot-6
maven_group=com.meander.subtlyd
archives_base_name=subtlyd

# Dependencies
fabric_version=0.158.0+26.3