name: Publish Mod

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Data Generator
        run: ./gradlew runDatagen

      - name: Build Jar
        run: ./gradlew build

      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: c65QHwL5
          name: ${{ github.event.release.name }}
          version: ${{ github.event.release.tag_name }}
          channel: beta
          featured: true
          changelog: ${{ github.event.release.body }}
          loaders: '["fabric"]'
          game-versions: '["26.1-snapshot-3"]'
          files: '["build/libs/subtlyd-${{ github.event.release.tag_name }}.jar"]'
          # Fabric API
          dependencies: |-
            [{
              "project_id": "P7dR8mSH",
              "dependency_type": "required"
            }]
          status: listed

      - name: Publish to Curseforge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: 1363308
          display_name: ${{ github.event.release.name }}
          release_type: beta
          changelog: ${{ github.event.release.body }}
          game_versions: "Minecraft 26.1-snapshot,Java 25,Fabric"
          file_path: "build/libs/subtlyd-${{ github.event.release.tag_name }}.jar"
          relations: "fabric-api:requiredDependency"
          game_endpoint: minecraft
