name: Scheduler

on:
  schedule:
    - cron: "0 14 9 1 *" # The planned date on Friday [MIN HOUR DAY MONTH WEEKDAY] at 2:00PM UTC

jobs:
  check-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish if Draft Exists
        env:
          GH_TOKEN: ${{ secrets.YOUR_PERSONAL_ACCESS_TOKEN }}
        run: |
          LATEST_DRAFT=$(gh release list --json isDraft,tagName --jq 'map(select(.isDraft)) | .[0].tagName') # Find draft
          
          if [ -z "$LATEST_DRAFT" ]; then
            echo "No draft found."
            exit 0
          fi
          
          echo "Publishing $LATEST_DRAFT." 
          gh release edit "$LATEST_DRAFT" --draft=false # Publish